### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by lmiroslaw** [Microsoft/KubeGPU#17]
Could you be more specific on how to install the project? I guess I need go, are there any other dependencies?

**Comment by resouer** [comment]
Hi @lmiroslaw , we will release binaries for users with guidance of how to install these plugins for existing Kubernetes cluster (just need to deploy several Pods etc). So basically, there's no dependencies.

**Comment by resouer** [comment]
And if you are looking for the whole solution because, for example, you are not familiar with Kubernetes at all. Then I would suggest to use https://github.com/Microsoft/DLworkspace which is the parent project for this repo, which handles Kubernetes installation, plugins (KubeGPU) installation, and with web UI.

DLworkspace is already ready to use right now and you can try it with any cloud provider or even baremetal. While I guess you may want to play with Azure :)

**Comment by lmiroslaw** [comment]
Thanks @resouer. The project will be useful for my projects.

**Comment by sanjeevm0** [comment]
Also, if you are just interested in GPU topology, you can use the binaries built here or build from the DLWorkspace project. It is fairly easy to build a docker image which contains all the needed binaries by using the DLWorkspace project. If you wish to add additional devices, then you can use the code here to add support for more devices/resources into a Kubernetes cluster.
